enum WebSocketEventEnum {
  CURRENT_MOVE_PLAYER_CHANGE = 'CURRENT_MOVE_PLAYER_CHANGE',
  ROLL_DICES = 'ROLL_DICES',
  MOVE_TO_CELL = 'MOVE_TO_CELL',
  PLAYER_ON_VACANT_PROPERTY = 'PLAYER_ON_VACANT_PROPERTY',
  PROPERTY_PURCHASE_OFFER = 'PROPERTY_PURCHASE_OFFER',
  PLAYER_ACCEPT_PURCHASE_OFFER = 'PLAYER_ACCEPT_PURCHASE_OFFER',
  PLAYER_DECLINE_PURCHASE_OFFER = 'PLAYER_DECLINE_PURCHASE_OFFER',
  PLAYER_ON_CHANCE_CELL = 'PLAYER_ON_CHANCE_CELL',
  PLAYER_ON_TAX_CELL = 'PLAYER_ON_TAX_CELL',
  PLAYER_BALANCE_CHANGE = 'PLAYER_BALANCE_CHANGE',
}

export default WebSocketEventEnum;
