enum WebSocketEventEnum {
  CURRENT_MOVE_PLAYER_CHANGE = 'CURRENT_MOVE_PLAYER_CHANGE',
  ROLL_DICES = 'ROLL_DICES',
  MOVE_TO_CELL = 'MOVE_TO_CELL',
  PLAYER_ON_NOT_BOUGHT_PROPERTY = 'PLAYER_ON_NOT_BOUGHT_PROPERTY',
  PROPERTY_PURCHASE_OFFER = 'PROPERTY_PURCHASE_OFFER',
  PLAYER_ACCEPT_PURCHASE_OFFER = 'PLAYER_ACCEPT_PURCHASE_OFFER',
  PLAYER_DECLINE_PURCHASE_OFFER = 'PLAYER_DECLINE_PURCHASE_OFFER',
  PLAYER_ON_CHANCE_CELL = 'PLAYER_ON_CHANCE_CELL',
  PLAYER_ON_TAX_CELL = 'PLAYER_ON_TAX_CELL',
  PLAYER_BALANCE_CHANGE = 'PLAYER_BALANCE_CHANGE',
  LOBBY_JOIN = 'LOBBY_JOIN',
  LOBBY_LEAVE = 'LOBBY_LEAVE',
  LOBBY_DISSOLVE = 'LOBBY_DISSOLVE',
}

export default WebSocketEventEnum;
